[2019-12-13 19:07:44] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 61192b19-5f43-43ac-8470-afb24c07f6f3 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | 'нч2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:07:44] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 260, in get
    interfaces_case_dict = model_to_dict(interfaces_case)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\playhouse\shortcuts.py", line 115, in model_to_dict
    rel_obj = getattr(model, field.name)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1386, in __get__
    return self.get_object_or_id(instance)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1377, in get_object_or_id
    obj = self.rel_model.get(self.field.to_field == rel_id)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3220, in get
    return next(clone.execute())
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3274, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2939, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1035, in execute_sql
    "Error, sync query is not allowed! Call the `.set_allow_sync()` "
AssertionError: Error, sync query is not allowed! Call the `.set_allow_sync()` or use the `.allow_sync()` context manager.
[2019-12-13 19:07:44] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-13 19:07:47] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | acb05498-0b48-4c41-948a-efbc860ef48f 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | 'нч2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:07:48] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 260, in get
    interfaces_case_dict = model_to_dict(interfaces_case)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\playhouse\shortcuts.py", line 115, in model_to_dict
    rel_obj = getattr(model, field.name)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1386, in __get__
    return self.get_object_or_id(instance)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1377, in get_object_or_id
    obj = self.rel_model.get(self.field.to_field == rel_id)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3220, in get
    return next(clone.execute())
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3274, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2939, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1035, in execute_sql
    "Error, sync query is not allowed! Call the `.set_allow_sync()` "
AssertionError: Error, sync query is not allowed! Call the `.set_allow_sync()` or use the `.allow_sync()` context manager.
[2019-12-13 19:07:48] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
