[2019-12-24 11:34:57] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzY4MzI4MTV9.sQQNRJBoSPADTJuoFhLd7fMD0Jg2yjuDpjZ8v38nVQA 
| User-Agent      | PostmanRuntime/7.21.0 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 01bee9c1-3478-4932-bf77-a7d91ea64718 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 67              
| Connection      | keep-alive      
+----Arguments----+
| 'suite_name'    | '12322222213'   
| 'cases'         | [33]            
| 'desc'          | '123123'        

[2019-12-24 11:34:57] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /suites/3/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/suites/3/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 69, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 710, in patch
    existed_suite.suite_name = form.test_name.data
AttributeError: 'TestSuiteForm' object has no attribute 'test_name'
[2019-12-24 11:34:57] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
