[2019-12-04 17:53:03] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 155, in prepare
    log_request(self)
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 54, in log_request
    request_body = ast.literal_eval(handler.request.body.decode('utf-8'))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x0000023E1389C208>
[2019-12-04 17:53:03] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-04 17:53:03] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 155, in prepare
    log_request(self)
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 54, in log_request
    request_body = ast.literal_eval(handler.request.body.decode('utf-8'))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x0000023E1389C248>
[2019-12-04 17:53:03] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-04 17:53:51] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzQ3NTIxNzd9.lsuunSK7H4MUPRRm-P6uWJxAqSpLvm7yJ6CS0LVBwa8 
| Content-Type    | application/x-www-form-urlencoded 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 1bd63b06-34a8-47fc-ba85-b96390020df4 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 244             
| Connection      | keep-alive      
+----Arguments----+
| 'interface_name' | '‘≤‘≤À¿≈÷◊”'         
| 'url'           | '123131'        
| 'method'        | 'get'           
| 'headers'       | '23113'         
| 'params'        | '32131'         
| 'assertion'     | '231413'        
| 'db'            | '2'             
| 'check_db'      | '123131'        
| 'response_extraction' | '23131'         
| 'project'       | '5'             
| 'desc'          | '21331'         

[2019-12-04 17:53:51] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| InterfacesHandler object has list index out of range
[2019-12-04 17:54:02] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 155, in prepare
    log_request(self)
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 54, in log_request
    request_body = ast.literal_eval(handler.request.body.decode('utf-8'))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x0000023E138FEE88>
[2019-12-04 17:54:02] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-04 17:54:02] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 155, in prepare
    log_request(self)
  File "F:\MagicTestPlatform\MagicTestPlatform\handlers.py", line 54, in log_request
    request_body = ast.literal_eval(handler.request.body.decode('utf-8'))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x0000023E139188C8>
[2019-12-04 17:54:02] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | GET             
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization   
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/functionManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| FunctionHandler object has list index out of range
[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Access-Control-Request-Method | GET             
| Origin          | http://localhost:8080 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Access-Control-Request-Headers | authorization   
| Accept          | */*             
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/functionManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  

[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | application/json 

Body:
| FunctionHandler object has list index out of range
[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/functionManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
| If-None-Match   | "bfa02d994775082feefaf132b0f7f1b5aa9d49a7" 

[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Undefined       | Undefined       

[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Host            | 127.0.0.1:8084  
| Connection      | keep-alive      
| Accept          | application/json, text/plain, */* 
| Origin          | http://localhost:8080 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| User-Agent      | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36 
| Sec-Fetch-Site  | cross-site      
| Sec-Fetch-Mode  | cors            
| Referer         | http://localhost:8080/functionManage 
| Accept-Encoding | gzip, deflate, br 
| Accept-Language | zh-CN,zh;q=0.9  
| If-None-Match   | "bfa02d994775082feefaf132b0f7f1b5aa9d49a7" 

[2019-12-04 17:54:06] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Undefined       | Undefined       

[2019-12-04 17:54:20] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzUwMjI1MzJ9.pTzgTRDJHyQfEiLyRTxhcDf10FBCvG0_eyP1Wv0pPzY 
| Content-Type    | application/x-www-form-urlencoded 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 239e76aa-5a39-4a5b-9efa-b8d8a5a46923 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 244             
| Connection      | keep-alive      
+----Arguments----+
| 'interface_name' | '‘≤‘≤À¿≈÷◊”'         
| 'url'           | '123131'        
| 'method'        | 'get'           
| 'headers'       | '23113'         
| 'params'        | '32131'         
| 'assertion'     | '231413'        
| 'db'            | '2'             
| 'check_db'      | '123131'        
| 'response_extraction' | '23131'         
| 'project'       | '5'             
| 'desc'          | '21331'         

[2019-12-04 17:54:20] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /interfaces/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/interfaces/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\apps\utils\wrappers.py", line 25, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 99, in get
    interfaces_query = Interfaces.extend()
  File "F:\MagicTestPlatform\apps\interface_test\models.py", line 44, in extend
    .join(DBSetting, join_type=JOIN.LEFT_OUTER, on=cls.db).switch(cls) \
AttributeError: type object 'Interfaces' has no attribute 'db'
[2019-12-04 17:54:21] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
