[2019-12-16 10:12:53] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 5533a646-f27d-4540-9f38-1676c5b415b1 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 145             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '込込込1'          
| 'interfaces'    | [10, 9]         
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-16 10:12:53] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /cases/4/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/cases/4/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 369, in patch
    await self.application.objects.update(existed_case)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 228, in update
    result = yield from self.execute(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 269, in execute
    return (yield from execute(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 433, in execute
    return (yield from coroutine(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 622, in update
    cursor = yield from _execute_query_async(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1558, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3450, in sql
    return self.compiler().generate_update(self)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2074, in generate_update
    return self.build_query(clauses, alias_map)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1929, in build_query
    return self.parse_node(Clause(*clauses), alias_map)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1774, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1907, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1774, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1907, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1745, in _parse_expression
    rhs, rparams = self.parse_node(node.rhs, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1761, in _parse_param
    return self.parse_node(node.adapt(node.value), alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1563, in db_value
    return self.to_field.db_value(value)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1018, in db_value
    return value if value is None else self.coerce(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
[2019-12-16 10:12:53] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-16 10:12:57] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 9c37593c-35cf-4a07-85d8-ca42870d5d6e 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 145             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '込込込1'          
| 'interfaces'    | [10, 9]         
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-16 10:12:57] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /cases/4/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/cases/4/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 369, in patch
    await self.application.objects.update(existed_case)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 228, in update
    result = yield from self.execute(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 269, in execute
    return (yield from execute(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 433, in execute
    return (yield from coroutine(query))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 622, in update
    cursor = yield from _execute_query_async(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee_async.py", line 1558, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3450, in sql
    return self.compiler().generate_update(self)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2074, in generate_update
    return self.build_query(clauses, alias_map)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1929, in build_query
    return self.parse_node(Clause(*clauses), alias_map)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1774, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1907, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1774, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1907, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1745, in _parse_expression
    rhs, rparams = self.parse_node(node.rhs, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1882, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1848, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1761, in _parse_param
    return self.parse_node(node.adapt(node.value), alias_map, conv)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1563, in db_value
    return self.to_field.db_value(value)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 1018, in db_value
    return value if value is None else self.coerce(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
[2019-12-16 10:12:57] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
