[2019-12-02 21:45:59] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzQ3NTIxNzd9.lsuunSK7H4MUPRRm-P6uWJxAqSpLvm7yJ6CS0LVBwa8 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | e39fb867-b762-4c43-80cf-8d7098fc1818 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 770             
| Connection      | keep-alive      

[2019-12-02 21:45:59] [ERROR] [MainThread] [handlers.py:105] Uncaught exception POST /interfaces_debug/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='POST', uri='/interfaces_debug/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\apps\utils\wrappers.py", line 25, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 48, in post
    param = json.loads(param)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 474 (char 742)
[2019-12-02 21:45:59] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
