[2019-12-24 11:34:04] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzY4MzI4MTV9.sQQNRJBoSPADTJuoFhLd7fMD0Jg2yjuDpjZ8v38nVQA 
| User-Agent      | PostmanRuntime/7.21.0 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | cc299aff-9411-4e01-9896-a26837ff3c5e 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 67              
| Connection      | keep-alive      
+----Arguments----+
| 'suite_name'    | '12322222213'   
| 'cases'         | [33]            
| 'desc'          | '123123'        

[2019-12-24 11:34:04] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /suites/33/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/suites/33/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 69, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 704, in patch
    form = TestSuite.from_json(param)
AttributeError: type object 'TestSuite' has no attribute 'from_json'
[2019-12-24 11:34:04] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-24 11:34:26] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzY4MzI4MTV9.sQQNRJBoSPADTJuoFhLd7fMD0Jg2yjuDpjZ8v38nVQA 
| User-Agent      | PostmanRuntime/7.21.0 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | aa41d313-531c-4ba8-86b7-62f194d68595 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 67              
| Connection      | keep-alive      
+----Arguments----+
| 'suite_name'    | '12322222213'   
| 'cases'         | [33]            
| 'desc'          | '123123'        

[2019-12-24 11:34:26] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /suites/3/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/suites/3/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 69, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 704, in patch
    form = TestSuite.from_json(param)
AttributeError: type object 'TestSuite' has no attribute 'from_json'
[2019-12-24 11:34:26] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-24 11:34:28] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzY4MzI4MTV9.sQQNRJBoSPADTJuoFhLd7fMD0Jg2yjuDpjZ8v38nVQA 
| User-Agent      | PostmanRuntime/7.21.0 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | c19d2df3-4649-4ce7-9690-9a11a644380a 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 67              
| Connection      | keep-alive      
+----Arguments----+
| 'suite_name'    | '12322222213'   
| 'cases'         | [33]            
| 'desc'          | '123123'        

[2019-12-24 11:34:28] [ERROR] [MainThread] [handlers.py:105] Uncaught exception PATCH /suites/3/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='PATCH', uri='/suites/3/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 69, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 704, in patch
    form = TestSuite.from_json(param)
AttributeError: type object 'TestSuite' has no attribute 'from_json'
[2019-12-24 11:34:28] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
