[2019-12-13 19:09:58] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 2e9996f4-dc70-4179-a106-118279849886 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '无2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:09:58] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 255, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == int(case.get('id')))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3218, in get
    clone = self.paginate(1, 1)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 401, in inner
    clone = self.clone()  # Assumes object implements `clone`.
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2798, in clone
    return self._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3036, in _clone_attributes
    query = super(SelectQuery, self)._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2802, in _clone_attributes
    query._where = self._where.clone()
AttributeError: 'str' object has no attribute 'clone'
[2019-12-13 19:09:58] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-13 19:10:00] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | 32097039-0a66-4d52-9af7-d83d5507c5b0 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '无2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:10:00] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 255, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == int(case.get('id')))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3218, in get
    clone = self.paginate(1, 1)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 401, in inner
    clone = self.clone()  # Assumes object implements `clone`.
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2798, in clone
    return self._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3036, in _clone_attributes
    query = super(SelectQuery, self)._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2802, in _clone_attributes
    query._where = self._where.clone()
AttributeError: 'str' object has no attribute 'clone'
[2019-12-13 19:10:00] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-13 19:10:01] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | dc71ea02-60c8-400c-93f6-4d7cad42b122 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '无2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:10:01] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 255, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == int(case.get('id')))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3218, in get
    clone = self.paginate(1, 1)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 401, in inner
    clone = self.clone()  # Assumes object implements `clone`.
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2798, in clone
    return self._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3036, in _clone_attributes
    query = super(SelectQuery, self)._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2802, in _clone_attributes
    query._where = self._where.clone()
AttributeError: 'str' object has no attribute 'clone'
[2019-12-13 19:10:01] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
[2019-12-13 19:10:02] [INFO] [MainThread] [handlers.py:63] Request Infomations:
+-----Headers-----+
| Content-Type    | application/json 
| Authorization   | eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmlja19uYW1lIjpudWxsLCJleHAiOjE1NzYyMjI3NTR9.KdwdPYH43DI8Qt2bY08dEz5fUhB-lnD5S3NCS2iF4fo 
| User-Agent      | PostmanRuntime/7.20.1 
| Accept          | */*             
| Cache-Control   | no-cache        
| Postman-Token   | e28eebdd-439f-41e4-8e37-d582a66d3692 
| Host            | 127.0.0.1:8084  
| Accept-Encoding | gzip, deflate   
| Content-Length  | 141             
| Connection      | keep-alive      
+----Arguments----+
| 'test_name'     | '无2221'         
| 'interfaces'    | [8, 9]          
| 'assertion'     | '12313'         
| 'db'            | 2               
| 'check_db'      | '123'           
| 'desc'          | '21q313132'     

[2019-12-13 19:10:02] [ERROR] [MainThread] [handlers.py:105] Uncaught exception GET /cases/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8084', method='GET', uri='/cases/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\MagicTestPlatform\common\core.py", line 37, in wrapper
    await method(self, *args, **kwargs)
  File "F:\MagicTestPlatform\apps\interface_test\handlers.py", line 255, in get
    interfaces_case_query = interfaces_case_query.filter(InterfacesTestCase.cases == int(case.get('id')))
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 4988, in get
    return sq.get()
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3218, in get
    clone = self.paginate(1, 1)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 401, in inner
    clone = self.clone()  # Assumes object implements `clone`.
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2798, in clone
    return self._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 3036, in _clone_attributes
    query = super(SelectQuery, self)._clone_attributes(query)
  File "D:\Users\Null\AppData\Local\Continuum\miniconda3\lib\site-packages\peewee.py", line 2802, in _clone_attributes
    query._where = self._where.clone()
AttributeError: 'str' object has no attribute 'clone'
[2019-12-13 19:10:02] [INFO] [MainThread] [handlers.py:44] Response Infomations:
+-----Headers-----+
| Content-Type    | text/plain      

Body:
| Traceback (most recent call last):
| 
